### ISSUE TITLE
Infinit loop on ezTable after last update

### ISSUE THREAD

**Issue by twoSGmbH** [rospdf/pdf-php#115]
Hello,
it seems like there is a bug since the last update in december where under some circumstances the ezTable (in detail it's the while in line 1941 Cezpdf) get's stuck in an infinit loop. we could not determine the correct circumstances under which the bug appears.

did anyone else encounter this problem?

thanks in advance.

**Comment by twoSGmbH** [comment]
if the value of the headline array (param 2) is an empty string or something like this the problem appears, with an dummystring everything works fine.

**Comment by ole1986** [comment]
Similar issue with #113 which I still need to fix

**Comment by j-oliveras** [comment]
I have the same error.
This occurs on https://github.com/rospdf/pdf-php/blob/db50fadfbc1588d6063f501285aae2e3837d0725/src/Cezpdf.php#L1962
when addText returns the same text as input. I think this occurs if the size is less than the needed by the text (and cannot split because than has no space characters).
